# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/thiagofsr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3684.76/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/thiagofsr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3684.76/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thiagofsr/Hacking/UFPB/GraphColoring

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thiagofsr/Hacking/UFPB/GraphColoring

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/thiagofsr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3684.76/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/thiagofsr/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3684.76/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiagofsr/Hacking/UFPB/GraphColoring/CMakeFiles /home/thiagofsr/Hacking/UFPB/GraphColoring/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thiagofsr/Hacking/UFPB/GraphColoring/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GraphColoring

# Build rule for target.
GraphColoring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GraphColoring
.PHONY : GraphColoring

# fast build rule for target.
GraphColoring/fast:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/build
.PHONY : GraphColoring/fast

Construction_Heuristic/Dsatur.o: Construction_Heuristic/Dsatur.cpp.o

.PHONY : Construction_Heuristic/Dsatur.o

# target to build an object file
Construction_Heuristic/Dsatur.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Construction_Heuristic/Dsatur.cpp.o
.PHONY : Construction_Heuristic/Dsatur.cpp.o

Construction_Heuristic/Dsatur.i: Construction_Heuristic/Dsatur.cpp.i

.PHONY : Construction_Heuristic/Dsatur.i

# target to preprocess a source file
Construction_Heuristic/Dsatur.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Construction_Heuristic/Dsatur.cpp.i
.PHONY : Construction_Heuristic/Dsatur.cpp.i

Construction_Heuristic/Dsatur.s: Construction_Heuristic/Dsatur.cpp.s

.PHONY : Construction_Heuristic/Dsatur.s

# target to generate assembly for a file
Construction_Heuristic/Dsatur.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Construction_Heuristic/Dsatur.cpp.s
.PHONY : Construction_Heuristic/Dsatur.cpp.s

FileReader/FileReader.o: FileReader/FileReader.cpp.o

.PHONY : FileReader/FileReader.o

# target to build an object file
FileReader/FileReader.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/FileReader/FileReader.cpp.o
.PHONY : FileReader/FileReader.cpp.o

FileReader/FileReader.i: FileReader/FileReader.cpp.i

.PHONY : FileReader/FileReader.i

# target to preprocess a source file
FileReader/FileReader.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/FileReader/FileReader.cpp.i
.PHONY : FileReader/FileReader.cpp.i

FileReader/FileReader.s: FileReader/FileReader.cpp.s

.PHONY : FileReader/FileReader.s

# target to generate assembly for a file
FileReader/FileReader.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/FileReader/FileReader.cpp.s
.PHONY : FileReader/FileReader.cpp.s

Graph/Graph.o: Graph/Graph.cpp.o

.PHONY : Graph/Graph.o

# target to build an object file
Graph/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Graph/Graph.cpp.o
.PHONY : Graph/Graph.cpp.o

Graph/Graph.i: Graph/Graph.cpp.i

.PHONY : Graph/Graph.i

# target to preprocess a source file
Graph/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Graph/Graph.cpp.i
.PHONY : Graph/Graph.cpp.i

Graph/Graph.s: Graph/Graph.cpp.s

.PHONY : Graph/Graph.s

# target to generate assembly for a file
Graph/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Graph/Graph.cpp.s
.PHONY : Graph/Graph.cpp.s

Node/Node.o: Node/Node.cpp.o

.PHONY : Node/Node.o

# target to build an object file
Node/Node.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Node/Node.cpp.o
.PHONY : Node/Node.cpp.o

Node/Node.i: Node/Node.cpp.i

.PHONY : Node/Node.i

# target to preprocess a source file
Node/Node.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Node/Node.cpp.i
.PHONY : Node/Node.cpp.i

Node/Node.s: Node/Node.cpp.s

.PHONY : Node/Node.s

# target to generate assembly for a file
Node/Node.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/Node/Node.cpp.s
.PHONY : Node/Node.cpp.s

PermutationHeuristic/ColorClassHeuristic.o: PermutationHeuristic/ColorClassHeuristic.cpp.o

.PHONY : PermutationHeuristic/ColorClassHeuristic.o

# target to build an object file
PermutationHeuristic/ColorClassHeuristic.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/PermutationHeuristic/ColorClassHeuristic.cpp.o
.PHONY : PermutationHeuristic/ColorClassHeuristic.cpp.o

PermutationHeuristic/ColorClassHeuristic.i: PermutationHeuristic/ColorClassHeuristic.cpp.i

.PHONY : PermutationHeuristic/ColorClassHeuristic.i

# target to preprocess a source file
PermutationHeuristic/ColorClassHeuristic.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/PermutationHeuristic/ColorClassHeuristic.cpp.i
.PHONY : PermutationHeuristic/ColorClassHeuristic.cpp.i

PermutationHeuristic/ColorClassHeuristic.s: PermutationHeuristic/ColorClassHeuristic.cpp.s

.PHONY : PermutationHeuristic/ColorClassHeuristic.s

# target to generate assembly for a file
PermutationHeuristic/ColorClassHeuristic.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/PermutationHeuristic/ColorClassHeuristic.cpp.s
.PHONY : PermutationHeuristic/ColorClassHeuristic.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/GraphColoring.dir/build.make CMakeFiles/GraphColoring.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GraphColoring"
	@echo "... Construction_Heuristic/Dsatur.o"
	@echo "... Construction_Heuristic/Dsatur.i"
	@echo "... Construction_Heuristic/Dsatur.s"
	@echo "... FileReader/FileReader.o"
	@echo "... FileReader/FileReader.i"
	@echo "... FileReader/FileReader.s"
	@echo "... Graph/Graph.o"
	@echo "... Graph/Graph.i"
	@echo "... Graph/Graph.s"
	@echo "... Node/Node.o"
	@echo "... Node/Node.i"
	@echo "... Node/Node.s"
	@echo "... PermutationHeuristic/ColorClassHeuristic.o"
	@echo "... PermutationHeuristic/ColorClassHeuristic.i"
	@echo "... PermutationHeuristic/ColorClassHeuristic.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

